spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/storage
    username: root
    password: P@ssw0rd1!
    driver-class-name: org.mariadb.jdbc.Driver

storage:
  files:
    url: "/upload/"
    path: "/var/opt/upload/"