spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/storage
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver

storage:
  files:
    url: "/upload/"
    path: "/rlawogud928/tomcat/upload/"