spring:
  profiles:
    active: local
  #    active: prod

  servlet:
    multipart:
      maxFileSize: 10MB     # 한개 파일 최대 용량
      maxRequestSize: 100MB # 한번 업로드 최대 용량

  jpa:
    hibernate:
      ddl-auto: update # create/update
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100
  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 2000

logging.level:
  org.hibernate.SQL: debug
#  org.hibernate.type: trace